// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package bifrost

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "ali.kaviani@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Pod/Container health check",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Pod/Container health check",
                "operationId": "handle_health_check",
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.HealthCheckResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            }
        },
        "/v1/applications/{APP_UUID}/users/{EXTERNAL_USER_ID}": {
            "put": {
                "description": "Update an existing device's tags in one of your Ratatoskr apps using the External User ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Update an existing device's tags in one of your Ratatoskr apps using the External User ID.",
                "operationId": "handle_edit_user_tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App Unique Identifier UUID",
                        "name": "APP_UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "External User ID",
                        "name": "EXTERNAL_USER_ID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List of User Tags",
                        "name": "UserTags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UserTagRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices": {
            "get": {
                "security": [
                    {
                        "APIKey": []
                    }
                ],
                "description": "View the details of multiple devices in one of your Ratatoskr apps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "View the details of multiple devices in one of your Ratatoskr apps",
                "operationId": "handle_view_devices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of device",
                        "name": "app_uuid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "How many devices to return. Max is 300. Default is 300",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Previous max record id.Default is 0. Results are sorted by id;",
                        "name": "last_device_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/handlers.DeviceViewResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Register a new device to one of your Ratatoskr apps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Register a new device to one of your Ratatoskr apps",
                "operationId": "handle_add_device",
                "parameters": [
                    {
                        "description": "Create Device Request",
                        "name": "Device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices/{UUID}": {
            "put": {
                "description": "Update an existing device in one of your Ratatoskr apps",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Update an existing device in one of your Ratatoskr apps",
                "operationId": "handle_edit_device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Unique Identifier",
                        "name": "UUID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create Device Request",
                        "name": "Device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            }
        },
        "/v1/devices/{uuid}/{app_uuid}": {
            "get": {
                "description": "View the details of an existing device in one of your Ratatoskr apps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "View the details of an existing device in one of your Ratatoskr apps",
                "operationId": "handle_view_device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID of application",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID of device",
                        "name": "app_uuid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Result",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/rest.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/handlers.DeviceViewResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.StandardResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.DeviceRequest": {
            "type": "object",
            "required": [
                "app_id",
                "device_type",
                "identifier"
            ],
            "properties": {
                "adid": {
                    "type": "string",
                    "example": "dbdf14cc-a5e7-445f-a972-2112ab335b14"
                },
                "app_id": {
                    "type": "string",
                    "example": "407f8f90-d83b-4ad5-912c-556a27c8f249"
                },
                "app_version": {
                    "type": "string",
                    "example": "2.1.1"
                },
                "country": {
                    "type": "string",
                    "example": "IR"
                },
                "device_model": {
                    "type": "string",
                    "example": "SM-989F"
                },
                "device_os": {
                    "type": "string",
                    "example": "Android"
                },
                "device_os_version": {
                    "type": "string",
                    "example": "8.0"
                },
                "device_type": {
                    "type": "string",
                    "example": "android | ios | web"
                },
                "device_vendor": {
                    "type": "string",
                    "example": "Samsung"
                },
                "external_user_id": {
                    "type": "string",
                    "example": "u-12"
                },
                "external_user_id_hash": {
                    "type": "string",
                    "example": "xxxxxxxx"
                },
                "identifier": {
                    "type": "string",
                    "example": "APA91bHbYHk7aq-Uam_2pyJ2qbZvqllyyh2wjfPRaw5gLEX2SUlQBRvOc6sck1sa7H7nGeLNlDco8lXj83HWWwzV..."
                },
                "language": {
                    "type": "string",
                    "example": "fa"
                },
                "lat": {
                    "type": "number",
                    "example": 54.123456
                },
                "long": {
                    "type": "number",
                    "example": 35.123456
                },
                "notification_types": {
                    "type": "integer",
                    "example": 1
                },
                "sdk": {
                    "type": "string",
                    "example": "1.0"
                },
                "session_count": {
                    "type": "integer",
                    "example": 1
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timezone": {
                    "type": "integer",
                    "example": 12600
                }
            }
        },
        "handlers.DeviceViewResponse": {
            "type": "object",
            "properties": {
                "adid": {
                    "type": "string",
                    "example": "dbdf14cc-a5e7-445f-a972-2112ab335b14"
                },
                "app_version": {
                    "type": "string",
                    "example": "2.1.1"
                },
                "badge_count": {
                    "type": "integer",
                    "example": 1
                },
                "created_at": {
                    "type": "string"
                },
                "device_model": {
                    "type": "string",
                    "example": "SM-989F"
                },
                "device_os": {
                    "type": "string",
                    "example": "Android"
                },
                "device_os_version": {
                    "type": "string",
                    "example": "8.0"
                },
                "device_type": {
                    "type": "string",
                    "example": "android | ios | web"
                },
                "device_vendor": {
                    "type": "string",
                    "example": "Samsung"
                },
                "external_user_id": {
                    "type": "string",
                    "example": "u-12"
                },
                "identifier": {
                    "type": "string",
                    "example": "APA91bHbYHk7aq-Uam_2pyJ2qbZvqllyyh2wjfPRaw5gLEX2SUlQBRvOc6sck1sa7H7nGeLNlDco8lXj83HWWwzV..."
                },
                "language": {
                    "type": "string",
                    "example": "fa"
                },
                "last_active_at": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "timezone": {
                    "type": "integer",
                    "example": 12600
                }
            }
        },
        "handlers.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "binary_uptime": {
                    "type": "string"
                },
                "build_time": {
                    "type": "string"
                },
                "container": {
                    "type": "string"
                },
                "git_commit": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "kernel_uptime": {
                    "type": "string"
                },
                "load_average_fifteen": {
                    "type": "number"
                },
                "load_average_five": {
                    "type": "number"
                },
                "load_average_one": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.UserTagRequest": {
            "type": "object",
            "required": [
                "tags"
            ],
            "properties": {
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "rest.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer",
                    "example": 0
                }
            }
        }
    },
    "securityDefinitions": {
        "APIKey": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:6060",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Ratatoskr(Bifrost)",
	Description: "Ratatoskr SDK Public REST APIs(Bifrost)",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
